### PR TITLE
Corrections ( the comment shows what )

### PR DESCRIPTION
**Pull request by thedeibo**
* Typos
* PHP change
* Directory Chage ( typo)
* tweaked plugin.yml
* MEHHH

### CODE REVIEW

**Comment by Driesboy** [comment]
thanks for helping

**Comment by Driesboy** [comment]
can you help me with joinhealth please

**Comment by thedeibo** [comment]
JoinHealth.......... ill see what I can do. but im not promising.

**Comment by thedeibo** [comment]
Ok. I hope this plugin works for you. if it doesn't, please email me at damian@iamdamian.tk

**Comment by Driesboy** [comment]
ok

**Comment by Driesboy** [comment]
can you help me to fix myplugin JoinHealth

**Comment by thedeibo** [comment]
Yep. I am going to make a start now.

**Comment by thedeibo** [comment]
Just making sure, does the plugin work ( InvisableJoin )
????

**Comment by Driesboy** [comment]
I dont have test 
I go it test after 20 min

**Comment by thedeibo** [comment]
Ok, ill also do it.

**Comment by Driesboy** [comment]
Work?

**Comment by thedeibo** [comment]
Well, its not invisible. Come see for yourself on play.thedeibomc.tk 19132

**Pull request merged**
